-- Scheduled for deprecation in 1.4.0

return {
	--[[
	["Example"] = {
		["Name"] = "Example",
		["Creator"] = "InfiniteStore",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/example.plugin.luau",
		["Commands"] = {"command1"},
	},
	]]
	--

	["FakeChat"] = {
		["Name"] = "FakeChat",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/FakeChat.plugin.luau",
		["Commands"] = { "fakechat / fchat [plr] [msg]" },
	},

	["Climb"] = {
		["Name"] = "Climb",
		["Creator"] = "bowla",
		["CreationDate"] = "06/09/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/climb.plugin.luau",
		["Commands"] = { "climb", "unclimb" },
	},

	["DarkDex"] = {
		["Name"] = "DarkDex",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/DarkDex.plugin.luau",
		["Commands"] = { "darkdex" },
	},

	["CamMaker"] = {
		["Name"] = "CamMaker",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/CamMaker.plugin.luau",
		["Commands"] = {
			"viewcam / vc [name]",
			"makecam / mc [name]",
			"delcam / dc [name]",
			"listcams / lc",
			"unviewcam / unvc",
		},
	},

	["Freecam2"] = {
		["Name"] = "Freecam2",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/Freecam2.plugin.luau",
		["Commands"] = { "freecam2 / fc2", "resetcam2 / rc2" },
	},

	["FunGrav"] = {
		["Name"] = "FunGrav",
		["Creator"] = "Thomas_Cornez",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/FunGrav.plugin.luau",
		["Commands"] = {
			"nogravparts",
			"gravparts",
			"supergravparts",
			"invertgravparts",
			"pushparts",
			"bombparts",
			"deleteunanchored / deleteua / cleanua",
			"moveparts [plr]",
			"movepartsmouse",
			"unmoveparts",
			"setblackhole",
			"blackhole",
			"removeblackhole",
			"stopblackhole",
			"controlblackhole",
			"uncontrolblackhole",
			"bringblackhole",
			"blackholeplayer [plr]",
			"unblackholeplayer",
			"loopsim",
			"flingparts [plr]",
			"flinghats [plr]",
			"unflingparts / unspinparts",
			"spinparts [plr]",
			"selectparts",
			"resetselectedpartslist / rspl",
			"uselist (TOGGLE)",
			"spinpartsmouse",
			"flingpartsmouse",
			"partscollide (TOGGLE)",
			"blackholedestroyparts / bhdp (TOGGLE)",
			"earthquake",
			"unearthquake",
			"autoupdate",
		},
	},

	["ReloadIY"] = {
		["Name"] = "ReloadIY",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/Reload.plugin.luau",
		["Commands"] = { "reload / unload" },
	},

	["SLTC"] = {
		["Name"] = "SLTC",
		["Creator"] = "Thomas_Cornez",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/SLTC.plugin.luau",
		["Commands"] = { "TeamGUI / loadteamgui" },
	},

	["ShaderMod"] = {
		["Name"] = "ShaderMod",
		["Creator"] = "WeAreRump",
		["CreationDate"] = "01/29/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/ShaderMod.plugin.luau",
		["Commands"] = { "toggleshader / ts" },
	},

	["ShiftToSprint"] = {
		["Name"] = "ShiftToSprint",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/ShiftToSprint.plugin.luau",
		["Commands"] = { "sprintspeed [speed]", "noshifttosprint / nsts", "shifttosprint / sts" },
	},

	["UnloadIY"] = {
		["Name"] = "UnloadIY",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/Unload.plugin.luau",
		["Commands"] = { "unload" },
	},

	["AddAllPlugins"] = {
		["Name"] = "AddAllPlugins",
		["Creator"] = "prisj",
		["CreationDate"] = "04/09/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/addallplugins.plugin.luau",
		["Commands"] = { "addallplugins / aap" },
	},

	["AntiFling"] = {
		["Name"] = "AntiFling",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/antifling.plugin.luau",
		["Commands"] = { "antifling" },
	},

	["AntiKill"] = {
		["Name"] = "AntiKill",
		["Creator"] = "enville",
		["CreationDate"] = " 09/11/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/antikill.plugin.luau",
		["Commands"] = { "antikill", "unantikill", "tantikill" },
	},

	["Beyblade"] = {
		["Name"] = "Beyblade",
		["Creator"] = "human",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/beyblade.plugin.luau",
		["Commands"] = { "beyblade" },
	},

	["BigHead"] = {
		["Name"] = "BigHead",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "08/10/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/bighead.plugin.luau",
		["Commands"] = { "bighead/biggest / bigger / big" },
	},

	["BigSize"] = {
		["Name"] = "BigSize",
		["Creator"] = "Toon",
		["CreationDate"] = " 08/16/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/bigsize.plugin.luau",
		["Commands"] = { "bigsize" },
	},

	["BlankSay"] = {
		["Name"] = "BlankSay",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/blanksay.plugin.luau",
		["Commands"] = { "blanksay / blankchat" },
	},

	["BTools2"] = {
		["Name"] = "BTools2",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/btools2.plugin.luau",
		["Commands"] = { "cycbtools / btools2" },
	},

	["BuilderChat"] = {
		["Name"] = "BuilderChat",
		["Creator"] = "LuaLighter",
		["CreationDate"] = "08/08/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/builderchat.plugin.luau",
		["Commands"] = { "buildchat / bchat [UrMSG] [BmMSG]" },
	},

	["BypassAntiCheat"] = {
		["Name"] = "BypassAntiCheat",
		["Creator"] = "Toon",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/bypassAnticheats.plugin.luau",
		["Commands"] = { "bypasswalkspeed / bws", "bypassjumppower / bjp", "bypassteleport / btp", "bypasskick / bk" },
	},

	["Celestial"] = {
		["Name"] = "Celestial",
		["Creator"] = "epik",
		["CreationDate"] = "09/04/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/celestial.plugin.luau",
		["Commands"] = { "celestial" },
	},

	["ChatSpy"] = {
		["Name"] = "ChatSpy",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/chatspy.plugin.luau",
		["Commands"] = { "chatspy" },
	},

	["ChatTranslate"] = {
		["Name"] = "ChatTranslate",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/chattranslator.plugin.luau",
		["Commands"] = { "translate [translate chat]" },
	},

	["Crash"] = {
		["Name"] = "Crash",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/crash.plugin.luau",
		["Commands"] = { "crash" },
	},

	["CuteString"] = {
		["Name"] = "CuteString",
		["Creator"] = "crazydoomy",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/cutestring.plugin.luau",
		["Commands"] = { "cutestring / cuteify [string]" },
	},

	["DisplayNameRemover"] = {
		["Name"] = "DisplayNameRemover",
		["Creator"] = "ratticus",
		["CreationDate"] = "07/22/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/displayNameRemover.plugin.luau",
		["Commands"] = { "removedisplay / removedisplaynames / nodisplayname / ndn" },
	},

	["DragChat"] = {
		["Name"] = "DragChat",
		["Creator"] = "Orion",
		["CreationDate"] = "04/03/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/draggablechat.plugin.luau",
		["Commands"] = { "dragchat / dragc" },
	},

	["EnableBackPack"] = {
		["Name"] = "EnableBackPack",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/enablebackpack.plugin.luau",
		["Commands"] = { "enablebackpack" },
	},

	["GiveTools"] = {
		["Name"] = "GiveTools",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/givetools.plugin.luau",
		["Commands"] = { "givetools [plr]" },
	},

	["HidePlayers"] = {
		["Name"] = "HidePlayers",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/hidePlayers.plugin.luau",
		["Commands"] = { "showplrs [name]", "hideplrs [name]" },
	},

	["HubLoader"] = {
		["Name"] = "HubLoader",
		["Creator"] = "Toon",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/hubloader.plugin.luau",
		["Commands"] = { "owlhub", "darkhub", "psyhub" },
	},

	["InteractESP"] = {
		["Name"] = "InteractESP",
		["Creator"] = "ap",
		["CreationDate"] = "04/23/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/protogens/things-i-ll-probably-use@main/interactable%20objects%20esp%20plugin",
		["Commands"] = {
			"clickdetectoresp / clickesp / cdesp",
			"proximityesp / promptesp / ppesp",
			"touchinterestesp / touchesp / tesp",
			"seatesp / sesp",
			"unclickdetectoresp / uncdesp",
			"unproximityesp / unppesp",
			"untouchinterestesp / untouchesp / untesp",
			"unseatesp / unsesp",
		},
	},

	["JoinRandomPlace"] = {
		["Name"] = "JoinRandomPlace",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/joinrandomplace.plugin.luau",
		["Commands"] = { "joinplace [min] [max]" },
	},

	["KillSounds"] = {
		["Name"] = "KillSounds",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/killsounds.plugin.luau",
		["Commands"] = { "killsounds / ks" },
	},

	["LagServer"] = {
		["Name"] = "LagServer",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/lag.plugin.luau",
		["Commands"] = { "lagserver" },
	},

	["LofiMusic"] = {
		["Name"] = "LofiMusic",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/lofimusic.plugin.luau",
		["Commands"] = { "lofimusi / lofigui" },
	},

	["Marble"] = {
		["Name"] = "Marble",
		["Creator"] = "Unknown",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/marble.plugin.luau",
		["Commands"] = { "marble [size]" },
	},

	["Telekinesis"] = {
		["Name"] = "Telekinesis",
		["Creator"] = "Toon",
		["CreationDate"] = "05/01/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/tel.plugin.luau",
		["Commands"] = { "telekinesis / tel" },
	},

	["TextToEmojis"] = {
		["Name"] = "TextToEmojis",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "08/31/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/texttoemojis.plugin.luau",
		["Commands"] = { "texttoemojis" },
	},

	["UnanchoredTeleporter"] = {
		["Name"] = "UnanchoredTeleporter",
		["Creator"] = "epik",
		["CreationDate"] = "08/25/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/unanchored.plugin.luau",
		["Commands"] = { "unanchored" },
	},

	["Metahook"] = {
		["Name"] = "Metahook",
		["Creator"] = "Toon",
		["CreationDate"] = "08/27/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/metahook.plugin.luau",
		["Commands"] = { "metahook [name] [value]" },
	},

	["ToonESP"] = {
		["Name"] = "ToonESP",
		["Creator"] = "Toon",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/toonesp.plugin.luau",
		["Commands"] = { "toonesp" },
	},

	["Flashlight"] = {
		["Name"] = "Flashlight",
		["Creator"] = "Toon",
		["CreationDate"] = "07/21/2020",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/flashlight.plugin.luau",
		["Commands"] = { "flashlight" },
	},

	["VR"] = {
		["Name"] = "VR",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "10/16/2020",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/virtualreality.plugin.luau",
		["Commands"] = { "vr" },
	},

	["LoopLight"] = {
		["Name"] = "LoopLight",
		["Creator"] = "FatalSe7en",
		["CreationDate"] = "10/20/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/looplight.plugin.luau",
		["Commands"] = {
			"loopday / lday / ld",
			"unloopday / unlday / unld",
			"loopnight / lnight / ln",
			"unloopnight / unlnight/ unln",
			"loopnofog / lnofog / lnf / loopnf",
			"unloopnofog / unlnofog / unlnf / unloopnf",
		},
	},

	["ClearChat"] = {
		["Name"] = "ClearChat",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "10/20/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/clearchat.plugin.luau",
		["Commands"] = { "clearchat / clchat" },
	},

	["EarRape"] = {
		["Name"] = "EarRape",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "10/26/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/earrape.plugin.luau",
		["Commands"] = { "playsounds", "loopplaysounds", "unloopplaysounds", "check", "restartmusic" },
	},

	["SChat"] = {
		["Name"] = "SChat",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "11/04/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/schat.plugin.luau",
		["Commands"] = { "schat [text]" },
	},

	["FreeFall"] = {
		["Name"] = "FreeFall",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "11/09/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/FreeFall.plugin.luau",
		["Commands"] = { "freefall [height]", "bounce [height]" },
	},

	["nosound"] = {
		["Name"] = "nosound",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "11/12/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/nosound.plugin.luau",
		["Commands"] = { "nosound" },
	},

	["Orbit"] = {
		["Name"] = "Orbit",
		["Creator"] = "Amokah",
		["CreationDate"] = "11/18/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/Orbit.plugin.luau",
		["Commands"] = { "orbit [plr]", "unorbit", "orbitspeed / ospeed [speed]", "orbitdist / odist [distance]" },
	},

	["fakeify"] = {
		["Name"] = "fakeify",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "12/12/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/fakeify.plugin.luau",
		["Commands"] = { "fakeuser [user]", "fakeid [ID]", "fakedisplay [displayname]" },
	},

	["psyhub"] = {
		["Name"] = "psyhub",
		["Creator"] = "Psykek",
		["CreationDate"] = "Unknown",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/psyhub.plugin.luau",
		["Commands"] = { "psyhub" },
	},

	["ip"] = {
		["Name"] = "ip",
		["Creator"] = "komt",
		["CreationDate"] = "06/24/2020",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/ip.plugin.luau",
		["Commands"] = { "getip / gip [plr]" },
	},

	["MultiSkid"] = {
		["Name"] = "MultiSkid",
		["Creator"] = "BugNugget",
		["CreationDate"] = "12/17/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/MultiSkid.plugin.luau",
		["Commands"] = {
			"sharkbite",
			"prisonlife",
			"musclelegends",
			"beeswarmsim / beeswarm",
			"petsimx / psx",
			"murdermystery2 / mm2",
			"phantomforces / pf",
			"arsenal",
			"piggy / pig",
			"buildaboat / babft",
			"afs",
			"cattoware / cat",
			"lt2",
			"jailbreak / jb",
			"brokebonesiv",
			"shindolife / sl",
			"carcrushers / cc",
			"kat",
			"fleethefacility / ftf",
		},
	},

	["FurrTools"] = {
		["Name"] = "FurrTools",
		["Creator"] = "Furrtren",
		["CreationDate"] = "12/16/2021",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/FurrTools.plugin.luau",
		["Commands"] = {
			"fuckball",
			"boombox",
			"explode / boom",
			"fuckmap",
			"slowmo",
			"unslowmo / noslowmo",
			"fuckchar / fuckme / fuckplr",
		},
	},

	["CtrlLock"] = {
		["Name"] = "CtrlLock",
		["Creator"] = "Toon",
		["CreationDate"] = "1/26/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/ctrl_lock.plugin.luau",
		["Commands"] = { "controllock / ctrllock" },
	},
	["IY_Emotes+"] = {
		["Name"] = "IY_Emotes+",
		["Creator"] = "deuces#1961 & phoriah",
		["CreationDate"] = "08/11/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/IY_Emotes+.plugin.luau",
		["Commands"] = { "e_EMOTENAME" },
	},
	["Skateboard"] = {
		["Name"] = "Skateboard",
		["Creator"] = "west",
		["CreationDate"] = "1/29/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/skateboard.plugin.luau",
		["Commands"] = { "skateboard" },
	},

	["Aimbot"] = {
		["Name"] = "Aimbot",
		["Creator"] = "Help.Yourself",
		["CreationDate"] = "7/24/2020",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/aimbot.plugin.luau",
		["Commands"] = { "aimbot / aim" },
	},

	["ShowHealth"] = {
		["Name"] = "ShowHealth",
		["Creator"] = "YuKii",
		["CreationDate"] = "2/14/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/showhealth.plugin.luau",
		["Commands"] = { "health / hp [plr]" },
	},

	["gears"] = {
		["Name"] = "gears",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "3/4/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/gears.plugin.luau",
		["Commands"] = { "gear [id]" },
	},

	["settingscount"] = {
		["Name"] = "settingscount",
		["Creator"] = "prisj",
		["CreationDate"] = "4/5/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/settingscount.plugin.luau",
		["Commands"] = {},
	},

	["spotify"] = {
		["Name"] = "spotify",
		["Creator"] = "lun_4tic",
		["CreationDate"] = "4/6/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/spotify.plugin.luau",
		["Commands"] = {
			"setoauth [spotify oauth]",
			"play",
			"pause / stop",
			"setspotifyvolume / ssvolume [number 0-100]",
			"next",
			"previous / prev",
			"spotifygui",
		},
	},

	["antiflingunfling"] = {
		["Name"] = "antiflingunfling",
		["Creator"] = "sfr",
		["CreationDate"] = "4/8/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/antiflingunfling.plugin.luau",
		["Commands"] = { "antiflingunfling / afu" },
	},

	["hit13"] = {
		["Name"] = "hit1-3",
		["Creator"] = "Doctor",
		["CreationDate"] = "4/10/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/hit13.plugin.luau",
		["Commands"] = { "hit [1-3]" },
	},

	["rename"] = {
		["Name"] = "rename",
		["Creator"] = "NoobSploit",
		["CreationDate"] = "4/4/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/rename.plugin.luau",
		["Commands"] = { "rename [text]" },
	},

	["MinionMeme"] = {
		["Name"] = "MinionMeme",
		["Creator"] = "Empire",
		["CreationDate"] = "4/4/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/MinionMeme.plugin.luau",
		["Commands"] = { "minionmeme / minionm / minm", "minionmemeDESTROY / minionmdestroy / minmdestroy" },
	},

	["SaveLoadTools"] = {
		["Name"] = "SaveLoadTools",
		["Creator"] = "Empire",
		["CreationDate"] = "4/4/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/SaveLoadTools.plugin.luau",
		["Commands"] = { "savetools / savet", "loadtools / loadt" },
	},

	["blockself"] = {
		["Name"] = "blockself",
		["Creator"] = "Empire",
		["CreationDate"] = "4/11/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/blockself.plugin.luau",
		["Commands"] = { "blockself [delay]" },
	},

	["GotoFolder"] = {
		["Name"] = "GotoFolder",
		["Creator"] = "D7M",
		["CreationDate"] = "5/07/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/GotoFolder.plugin.luau",
		["Commands"] = { "gotofolder" },
	},

	["Textures"] = {
		["Name"] = "Textures",
		["Creator"] = "WheresSilly",
		["CreationDate"] = "6/18/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/Textures.plugin.luau",
		["Commands"] = { "improvetextures", "undotextures" },
	},

	["FakeCommands"] = {
		["Name"] = "FakeCommands",
		["Creator"] = "Tyyuiss",
		["CreationDate"] = "6/18/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/fakecommands.plugin.luau",
		["Commands"] = { "fakekick / fkick <reason>", "fakeban / fban <reason>" },
	},

	["Keybinds"] = {
		["Name"] = "KeybindsV2",
		["Creator"] = "Thomas_Cornez",
		["CreationDate"] = "06/27/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/Keybinds.plugin.luau",
		["Commands"] = { "bind {key} {command} [argument] {command} [argument]", "unbind {key}" },
	},

	["Prediction"] = {
		["Name"] = "Prediction",
		["Creator"] = "Toon",
		["CreationDate"] = "07/03/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/prediction.plugin.luau",
		["Commands"] = {},
	},

	["Notify+"] = {
		["Name"] = "Notify+",
		["Creator"] = "epik",
		["CreationDate"] = "08/13/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/notify+.plugin.luau",
		["Commands"] = {},
	},
	["Tween Fly"] = {
		["Name"] = "Tween Fly",
		["Creator"] = "Quan",
		["CreationDate"] = "08/16/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/tfly.plugin.luau",
		["Commands"] = { "tfly [speed]", "untfly" },
	},
	["Execute"] = {
		["Name"] = "Executor",
		["Creator"] = "epik",
		["CreationDate"] = "08/27/2022",
		["GithubLink"] = "https://cdn.jsdelivr.net/gh/Infinite-Store/Infinite-Store@main/plugins/execute.plugin.luau",
		["Commands"] = { "execute / exec / script / s" },
	},
}
